### ISSUE TITLE
Set the seed that portals lead to

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [vicjohnson1213/Superflight-Mods#28]
It would be cool if we could manually set the seed that the ingame portals take you to.  I have several reasons for wanting this, one of them being the discovery of glitched seeds that can be explored if randomly encountered through a portal but prevent the main menu from working if entered from the initial spawn point.

**Comment by vicjohnson1213** [comment]
This is an interesting idea - one that I'll explore a little bit. Maybe a file with a list of seeds to use as you move from one world to the next?

**Comment by SlyCooperReloadCoded** [comment]
Oh, this project isn't dead, excellent - because the game's general community seems to be.  Yes, that's a perfect idea, a list would be great.  This will help me on my investigation on broken seeds as well as just adding playlists would be cool.

**Comment by vicjohnson1213** [comment]
@SlyCooperReloadCoded Here you go: https://github.com/vicjohnson1213/Superflight-Mods/tree/master/NextSeeds

It should be there when you open SFMF now. Great suggestion.

**Comment by SlyCooperReloadCoded** [comment]
Two problems:

1.  Can the NextSeeds.txt be placed next to the SFMF executable instead of in the file path shown?

2.  Can the list of seeds start over from the beginning when it reaches the end of the list?

**Comment by vicjohnson1213** [comment]
Should be doable.
