### ISSUE TITLE
Ability to customize flyer

### ISSUE THREAD

**Issue by Trash-Punk** [vicjohnson1213/Superflight-Mods#29]
If we could get a mod that would allow you to change the color, or person flying, that would be pretty cool. I do not know if this is possible, as I am a novice coder and haven't even opened up the games files to look yet. But, I did think it would be a fun feature to mod in, if possible.

**Comment by vicjohnson1213** [comment]
Great suggestion. I spent a little time exploring this and it looks like it should be possible. It'll take me some time to get it working with settings and such. Stay tuned for a release of this mod.

**Comment by vicjohnson1213** [comment]
Completed with baca29a
